#!/bin/bash
export MESOS_NATIVE_LIBRARY=/usr/local/lib/libmesos.so
export SPARK_JAVA_OPTS="-XX:+UseConcMarkSweepGC -Dspark.cleaner.delay=100"
export SPARK_MEM=30g
java -Dspark.local.dir=/dev/ampcamp/tmp,/dev/shm/ampcamp,/sapmnt/ampcamp -Xmx30g -XX:MaxPermSize=256m -jar $(dirname $0)/sbt-launch-*.jar "$@"
