#!/bin/bash
export MESOS_NATIVE_LIBRARY=/usr/local/lib/libmesos.so
java -Xmx30g -XX:MaxPermSize=256m $EXTRA_ARGS -Dspark.local.dir=/dev/ampcamp/tmp,/dev/shm/ampcamp,/sapmnt/ampcamp -jar $(dirname $0)/sbt-launch-*.jar "$@"
